/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import BaseDeDatos.Gestion;
import java.sql.DriverManager;
import javax.swing.ImageIcon;

public class updateObservacion extends javax.swing.JFrame {

    Gestion g;
    
    public updateObservacion() {
        initComponents();
        g = new Gestion();
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        color = new javax.swing.JCheckBox();
        armamento = new javax.swing.JCheckBox();
        art = new javax.swing.JCheckBox();
        manejable = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        color.setForeground(new java.awt.Color(255, 255, 0));
        color.setText("COLOR_LLAMATIVO");
        getContentPane().add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 180, -1));

        armamento.setForeground(new java.awt.Color(255, 255, 0));
        armamento.setText("ARMAMENTO_FUNCIONAL");
        getContentPane().add(armamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 180, -1));

        art.setForeground(new java.awt.Color(255, 255, 0));
        art.setText("ART_PERSONALIZADO");
        getContentPane().add(art, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 180, -1));

        manejable.setForeground(new java.awt.Color(255, 255, 0));
        manejable.setText("MANEJABLE");
        getContentPane().add(manejable, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 180, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("INGRESE EL ID DE LA OBSERVACION QUE DESEA MODIFICAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("ELIJA NUEVAS OBSERVACIONES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 80, 190, 20));

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fond.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ID1 = id.getText();
        String ID2 = "";
        
         if(color.isSelected())
            ID2 = ID2+"Color"+", ";
            if(armamento.isSelected())
                ID2 = ID2+"Armamento"+", ";
                else
                if(art.isSelected())
                    ID2 = ID2+"Art_Modificado"+", "; 
                        if(manejable.isSelected())
                        ID2 = ID2+"Manejable"+" ";
        
        g.updateDatosOBS(ID1, ID2);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateObservacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox armamento;
    private javax.swing.JCheckBox art;
    private javax.swing.JCheckBox color;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox manejable;
    // End of variables declaration//GEN-END:variables
}
